language: minimal

services:
  - docker

import:
  - source: Alfresco/alfresco-build-tools:.travis.docker_login.yml@v1.0.1

branches:
  only:
    - master
    - /feature.*/
    - /fix.*/
    - /OPSEXP-.*/

before_script:
  - export IMAGE_NAME=alfresco/alfresco-acs-nginx
  - export IMAGE_TAG=test

script:
  - docker build . -t $IMAGE_NAME:$IMAGE_TAG
  - docker images
  - |-
    if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_COMMIT_MESSAGE}" == *"[release]"* ]]
    then
      echo "Tagging and pushing to $IMAGE_NAME:$IMAGE_TAG..."
      docker push $IMAGE_NAME:$IMAGE_TAG
    fi